version: '3.7'
services:
  web:
    build: .
    depends_on:
      - db
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - './app:/app'
    ports:
      - '8000:8000'
  db:
    image: postgres
    ports:
      - '5432:5432'
    volumes:
      - ./dbdata:/var/lib/mysql